language: php
php:
  - 7.3
  - 7.4
before_script:
  - sudo apt-get -y install pdftk
  - composer install --no-interaction
  - mkdir -p build/logs
script: vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success: vendor/bin/php-coveralls -v
